<Project>
  <PropertyGroup>
    <Version>1.6.10.0</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <WarningLevel>9999</WarningLevel>
    <Company>Christopher Nenning</Company>
    <Copyright>Copyright © Christopher Nenning $([System.DateTime]::Now.Year)</Copyright>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
</Project>
